// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBbQsa4sRozmbF88XPKtGVuX8o6VRF2yc',
    appId: '1:917496097526:web:a3165d0d810f5ca09a1ad7',
    messagingSenderId: '917496097526',
    projectId: 'tarelchar',
    authDomain: 'tarelchar.firebaseapp.com',
    storageBucket: 'tarelchar.firebasestorage.app',
    measurementId: 'G-K2P23LCWWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBthwSVfbrUkxULFfIHo5laUjc6twTXEmg',
    appId: '1:917496097526:android:1addab2a6fe41f3e9a1ad7',
    messagingSenderId: '917496097526',
    projectId: 'tarelchar',
    storageBucket: 'tarelchar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOsQA6v0x4HHkZ0nsjzrlq1k-1HvV8eqs',
    appId: '1:917496097526:ios:782f5756233299b29a1ad7',
    messagingSenderId: '917496097526',
    projectId: 'tarelchar',
    storageBucket: 'tarelchar.firebasestorage.app',
    iosBundleId: 'com.example.tarElChar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOsQA6v0x4HHkZ0nsjzrlq1k-1HvV8eqs',
    appId: '1:917496097526:ios:782f5756233299b29a1ad7',
    messagingSenderId: '917496097526',
    projectId: 'tarelchar',
    storageBucket: 'tarelchar.firebasestorage.app',
    iosBundleId: 'com.example.tarElChar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBbQsa4sRozmbF88XPKtGVuX8o6VRF2yc',
    appId: '1:917496097526:web:ea93135c3ad7ae649a1ad7',
    messagingSenderId: '917496097526',
    projectId: 'tarelchar',
    authDomain: 'tarelchar.firebaseapp.com',
    storageBucket: 'tarelchar.firebasestorage.app',
    measurementId: 'G-R6F6XH31YT',
  );
}
